-- MySQL Script generated by MySQL Workbench
-- 04/28/16 12:29:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema legouShop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema legouShop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `legouShop` DEFAULT CHARACTER SET utf8 ;
USE `legouShop` ;

-- -----------------------------------------------------
-- Table `legouShop`.`legouShop_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `legouShop`.`legouShop_user` (
  `user_id` VARCHAR(16) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `username` VARCHAR(10) NOT NULL,
  `email` VARCHAR(20) NOT NULL,
  `telphone_num` VARCHAR(11) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`user_id`));


-- -----------------------------------------------------
-- Table `legouShop`.`legouShop_goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `legouShop`.`legouShop_goods` (
  `goods_id` INT(16) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `brand` VARCHAR(20) NOT NULL,
  `price` DECIMAL(9,2) NOT NULL,
  `amount` INT NOT NULL,
  `discount_status` TINYINT(1) NOT NULL DEFAULT 0,
  `discount_price` DECIMAL(9,2) NULL,
  `discount_amount` DECIMAL(9,2) NULL DEFAULT 0,
  `discount_start_time` INT NULL,
  `discount_end_time` INT NULL,
  `details` TEXT(5000) NULL,
  `message` TEXT(200) NULL,
  `more` TEXT(5000) NULL,
  `sale_num_month` INT NOT NULL DEFAULT 0,
  `total_sale_num` MEDIUMTEXT NOT NULL,
  `img1` VARCHAR(45) NOT NULL,
  `img2` VARCHAR(45) NOT NULL,
  `img3` VARCHAR(45) NOT NULL,
  `img4` VARCHAR(45) NOT NULL,
  `keyword` TEXT(100) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`goods_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `legouShop`.`legouShop_shoppingCart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `legouShop`.`legouShop_shoppingCart` (
  `user_id` VARCHAR(16) NOT NULL,
  `goods_id` INT(16) NOT NULL,
  `num` INT NOT NULL,
  `per_price` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`user_id`, `goods_id`),
  INDEX `fk_legouShop_user_has_legouShop_goods_legouShop_goods1_idx` (`goods_id` ASC),
  INDEX `fk_legouShop_user_has_legouShop_goods_legouShop_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_legouShop_user_has_legouShop_goods_legouShop_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `legouShop`.`legouShop_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_legouShop_user_has_legouShop_goods_legouShop_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `legouShop`.`legouShop_goods` (`goods_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `legouShop`.`legouShop_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `legouShop`.`legouShop_order` (
  `order_id` INT(16) NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(16) NOT NULL,
  `goods_id` INT(16) NOT NULL,
  `price` DECIMAL(9,2) NOT NULL,
  `num` INT NOT NULL,
  `logistics_num` VARCHAR(20) NULL,
  `create_time` DATETIME NOT NULL DEFAULT NOW(),
  INDEX `fk_legouShop_user_has_legouShop_goods_legouShop_goods2_idx` (`goods_id` ASC),
  INDEX `fk_legouShop_user_has_legouShop_goods_legouShop_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`order_id`),
  CONSTRAINT `fk_legouShop_user_has_legouShop_goods_legouShop_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `legouShop`.`legouShop_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_legouShop_user_has_legouShop_goods_legouShop_goods2`
    FOREIGN KEY (`goods_id`)
    REFERENCES `legouShop`.`legouShop_goods` (`goods_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
