-- MySQL Script generated by MySQL Workbench
-- 05/12/16 12:05:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema legoushop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema legoushop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `legoushop` DEFAULT CHARACTER SET utf8 ;
USE `legoushop` ;

-- -----------------------------------------------------
-- Table `legoushop`.`legoushop_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `legoushop`.`legoushop_user` (
  `user_id` VARCHAR(16) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `user_name` VARCHAR(10) NOT NULL,
  `email` VARCHAR(20) NOT NULL,
  `telphone_num` VARCHAR(11) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `create_time` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`));


-- -----------------------------------------------------
-- Table `legoushop`.`legoushop_goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `legoushop`.`legoushop_goods` (
  `goods_id` BIGINT(16) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `brand` VARCHAR(20) NOT NULL,
  `price` DECIMAL(9,2) NOT NULL,
  `color` TEXT(5) NOT NULL,
  `amount` INT NOT NULL,
  `discount_status` TINYINT(1) NOT NULL DEFAULT 0,
  `discount_price` DECIMAL(9,2) NULL,
  `discount_amount` DECIMAL(9,2) NULL DEFAULT 0,
  `discount_start_time` INT NULL,
  `discount_end_time` INT NULL,
  `details` TEXT(5000) NOT NULL,
  `message` TEXT(200) NULL,
  `more` TEXT(5000) NULL,
  `sale_num_month` INT NOT NULL DEFAULT 0,
  `total_sale_num` MEDIUMTEXT NOT NULL,
  `img1` VARCHAR(100) NOT NULL,
  `img2` VARCHAR(100) NOT NULL,
  `img3` VARCHAR(100) NOT NULL,
  `img4` VARCHAR(100) NOT NULL,
  `keyword` TEXT(100) NOT NULL,
  `create_time` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`goods_id`))
ENGINE = InnoDB AUTO_INCREMENT=1000000000000000;


-- -----------------------------------------------------
-- Table `legoushop`.`legoushop_shoppingCart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `legoushop`.`legoushop_shoppingCart` (
  `user_id` VARCHAR(16) NOT NULL,
  `goods_id` BIGINT(16) NOT NULL,
  `num` INT NOT NULL,
  `per_price` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`user_id`, `goods_id`),
  INDEX `fk_legoushop_user_has_legoushop_goods_legoushop_goods1_idx` (`goods_id` ASC),
  INDEX `fk_legoushop_user_has_legoushop_goods_legoushop_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_legoushop_user_has_legoushop_goods_legoushop_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `legoushop`.`legoushop_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_legoushop_user_has_legoushop_goods_legoushop_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `legoushop`.`legoushop_goods` (`goods_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `legoushop`.`legoushop_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `legoushop`.`legoushop_order` (
  `order_id` BIGINT(16) NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(16) NOT NULL,
  `goods_id` BIGINT(16) NOT NULL,
  `price` DECIMAL(9,2) NOT NULL,
  `num` INT NOT NULL,
  `logistics_num` VARCHAR(20) NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_legoushop_user_has_legoushop_goods_legoushop_goods2_idx` (`goods_id` ASC),
  INDEX `fk_legoushop_user_has_legoushop_goods_legoushop_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`order_id`),
  CONSTRAINT `fk_legoushop_user_has_legoushop_goods_legoushop_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `legoushop`.`legoushop_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_legoushop_user_has_legoushop_goods_legoushop_goods2`
    FOREIGN KEY (`goods_id`)
    REFERENCES `legoushop`.`legoushop_goods` (`goods_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) AUTO_INCREMENT=1000000000000000;


-- -----------------------------------------------------
-- Table `legoushop`.`legoushop_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `legoushop`.`legoushop_session` (
  `session_id` VARCHAR(255) NOT NULL,
  `session_expire` INT(11) NOT NULL,
  `session_data` BLOB NULL,
  UNIQUE INDEX `session_id_UNIQUE` (`session_id` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
